name: Tickcount
options:
  bundleIdPrefix: com.shimondeitel.tickremove
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "W7Q885Q59C"
    CODE_SIGN_STYLE: Automatic
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
targets:
  Tickcount:
    type: application
    platform: iOS
    sources:
      - path: Tickcount
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.tickremove
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: Tickcount/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: "YES"
        GENERATE_INFOPLIST_FILE: "NO"
  TickcountTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: TickcountTests
      - path: Tickcount.storekit
    dependencies:
      - target: Tickcount
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.tickremove.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
  TickcountUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: TickcountUITests
    dependencies:
      - target: Tickcount
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.tickremove.uitests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  Tickcount:
    build:
      targets:
        Tickcount: all
        TickcountTests: [test]
        TickcountUITests: [test]
    run:
      config: Debug
      storeKitConfiguration: Tickcount.storekit
    test:
      config: Debug
      storeKitConfiguration: Tickcount.storekit
      targets:
        - TickcountTests
        - TickcountUITests
    archive:
      config: Release
